// Builds <TEAM>_BGCCR3.pptx: cover, executive summary, 8 solution slides, 2 reference pages. All money numbers come from ../model/outputs/model_outputs.json
const fs = require('fs'); const path = require('path'); const pptxgen = require('pptxgenjs');
const { T,F,W,H,MX, table, text, rect, line, circle, sectionLabel, frame, takeaway, kpi, fmt } = require('./theme');
const M = JSON.parse(fs.readFileSync(path.join(__dirname,'../model/outputs/model_outputs.json'),'utf8'));
const B = M.base_totals, R = Object.fromEntries(M.rows_base.map(r=>[r.id,r])), P = M.pathways, U = M.units, Et = M.E_t, Es = M.E_s, SC = M.scenarios;
const TEAM = process.env.TEAM_NAME || 'TEAMNAME'; const MEMBERS = process.env.TEAM_MEMBERS || ''; const INSTITUTION = process.env.INSTITUTION || '';
const ph = (v, p) => v ? {text:v, options:{color:T.dark, bold:true}} : {text:p, options:{color:T.orange, bold:true}};
const warnings = []; const r0=(x)=>Math.round(x); const be = B.breakeven; const c2cac = r0(R.C2.cac_attributed);
function fit(name, used, max){ if(used>max+0.02) warnings.push(`${name}: needs ${used.toFixed(2)}in, has ${max.toFixed(2)}in`); }
const sc=(k,n)=>SC[n].totals[k];
(async () => {
const pres = new pptxgen(); pres.layout = 'LAYOUT_WIDE'; pres.author = TEAM; pres.company = TEAM; pres.title = 'Earn the Second Occasion: FanCode ATP growth (BGCC Case Consilium 2026, Round 3)';
// ------------------------------------------------------------------ 1 COVER
{ const s = pres.addSlide(); s.background = {color:T.white};
  s.addShape('rtTriangle', {x:8.9, y:0, w:4.433, h:3.2, fill:{color:T.pale}, line:{color:T.pale,width:0}, flipH:true});
  rect(s, 7.55, 0.75, 5.45, 6.05, {fill:T.deep, round:true, r:0.12});
  const cx=8.05, cy=1.2, cw=4.45, ch=5.0; const lc='9CC4F2';
  s.addShape('rect', {x:cx, y:cy, w:cw, h:ch, fill:{color:T.deep}, line:{color:lc, width:1.5}});
  const sx = cw*0.11; line(s, cx+sx, cy, cx+sx, cy+ch, {color:lc,width:1.25}); line(s, cx+cw-sx, cy, cx+cw-sx, cy+ch, {color:lc,width:1.25});
  const sy = ch*0.24; line(s, cx+sx, cy+sy, cx+cw-sx, cy+sy, {color:lc,width:1.25}); line(s, cx+sx, cy+ch-sy, cx+cw-sx, cy+ch-sy, {color:lc,width:1.25});
  line(s, cx+cw/2, cy+sy, cx+cw/2, cy+ch-sy, {color:lc,width:1.25}); line(s, cx-0.25, cy+ch/2, cx+cw+0.25, cy+ch/2, {color:T.white,width:2.5});
  circle(s, cx+cw*0.66, cy+ch*0.31, 0.42, T.orange);
  text(s, 'ATP Tour on FanCode: 56 events a year, exclusive in the Indian Subcontinent through 2028 (S1, S2)', {x:7.75, y:6.32, w:5.05, h:0.36, fontSize:9, color:'CFE3FA'});
  text(s, 'BGCC Case Consilium 2026  ·  Round 3  ·  Case partner: FanCode', {x:MX, y:0.75, w:7.0, h:0.3, fontFace:F.head, bold:true, fontSize:12, color:T.deep});
  s.addText([{text:'Earn the ', options:{color:T.dark}},{text:'Second Occasion', options:{color:T.blue}}], {isTextBox:true, x:MX, y:1.55, w:7.1, h:1.45, fontFace:F.head, bold:true, fontSize:40, margin:0, valign:'top', lineSpacingMultiple:0.98});
  rect(s, MX, 3.12, 0.75, 0.05, {fill:T.blue});
  text(s, 'Converting irregular ATP Tour interest into incremental, retained and profitable subscription growth for FanCode in India', {x:MX, y:3.35, w:6.9, h:0.9, fontSize:15, color:T.dark, lineSpacingMultiple:1.1});
  text(s, 'Buy intent, not reach. Sell the season, not the match. Prove the lift before scaling.', {x:MX, y:4.25, w:6.9, h:0.45, fontSize:12.5, italic:true, color:T.grey});
  rect(s, MX, 4.95, 6.9, 1.55, {fill:T.neutral, round:true, r:0.08});
  text(s, [{text:'Registered team: ', options:{bold:true, color:T.dark}}, ph(process.env.TEAM_NAME, '[ENTER EXACT REGISTERED TEAM NAME]'),{text:'', options:{breakLine:true}},
           {text:'Team members: ', options:{bold:true, color:T.dark}}, ph(MEMBERS, '[ENTER REGISTERED MEMBER NAMES]'),{text:'', options:{breakLine:true}},
           {text:'Institution: ', options:{bold:true, color:T.dark}}, ph(INSTITUTION, '[ENTER INSTITUTION, IF REQUIRED]')], {x:MX+0.2, y:5.05, w:6.5, h:1.35, fontSize:12, color:T.dark, valign:'middle', paraSpaceAfter:5});
  text(s, 'Submission deck, 12 pages: cover, executive summary, eight solution slides, two reference pages. Prices in ₹, times in IST.', {x:MX, y:6.85, w:7.1, h:0.3, fontSize:8.5, color:T.lightGrey});
}
// ------------------------------------------------------------------ 2 EXECUTIVE SUMMARY
{ const s = pres.addSlide();
  frame(s, {title:[{t:'Executive summary: '},{t:'buy intent, not reach; sell the season, not the match; prove the lift before scaling', a:true}], tag:'Executive summary', sub:'One page; forecasts are modelled, thresholds are proposed test targets', page:2,
    sources:'Case facts from the Round 3 brief (CF1-CF19, see References). Model: cohort and channel model, base case, ₹10 lakh illustrative pilot for 23 Sep-22 Nov 2026 (research/model in the support folder). CAC = customer acquisition cost per newly acquired paying subscriber; CRM = customer relationship management (owned channels).'});
  const ky=1.28, kh=0.98, kw=3.03, kg=0.17;
  kpi(s, MX, ky, kw, kh, {value:'₹150-₹200', label:'Case target CAC per new paying subscriber (CF9). Attributed and incremental CAC are reported separately.'});
  kpi(s, MX+kw+kg, ky, kw, kh, {value:fmt.inr(B.paid_ex_test_cac_attributed), label:`Modelled attributed CAC on the scalable paid rows (search/retargeting, contests), base case; ${fmt.inr(B.paid_blended_cac_attributed)} with the prospecting test.`});
  kpi(s, MX+2*(kw+kg), ky, kw, kh, {value:`${fmt.n(B.new_payers_attributed_dedup)} / ${fmt.n(B.incremental_new_payers)}`, label:'Attributed / incremental new payers from the ₹10 lakh pilot, deduplicated, base case (modelled).'});
  kpi(s, MX+3*(kw+kg), ky, kw, kh, {value:fmt.pct(be.be_upgrade_m24_cac183), label:`Upgrade share tournament-pass entrants need to repay ₹${c2cac} CAC within 24 months; base assumption 20%, ladder target 30%.`, color:T.orange});
  const lx=MX, lw=6.15, rx=6.75, rw=6.23; let y=2.42;
  sectionLabel(s, lx, y, lw, 'The commercial problem'); y+=0.3;
  text(s, 'ATP demand on FanCode is spiky: India-friendly Masters weeks index about 150 against 100 in ordinary weeks, marquee European evenings start at 00:00-01:00 IST, and about 90% of ordinary-week viewers are already fans. A ₹79-₹99 first purchase leaves roughly ₹62 of contribution before marketing, so it cannot repay ₹150-₹200 on its own, and organic F1/football growth confounds what performance spend is credited with. Trade-offs made: defer broad acquisition, cap overnight live-conversion spend, turn takeovers into a measured test.', {x:lx, y, w:lw, h:1.05, fontSize:9.8, lineSpacingMultiple:1.06}); y+=1.1;
  sectionLabel(s, lx, y, lw, 'Cohorts first'); y+=0.3;
  text(s, [{text:'1. ', options:{bold:true,color:T.blue}},{text:'Observable tennis intent that does not pay yet (free tennis viewers, tennis-page visitors, lapsed 2025 buyers): the only new-payer cohort worth paid media, and only at T-48h. '},{text:'2. ', options:{bold:true,color:T.blue}},{text:'Finish-the-Season buyers in marquee weeks (Shanghai, Paris, ATP Finals). '},{text:'3. ', options:{bold:true,color:T.blue}},{text:'F1, MotoGP and LaLiga pass holders, cross-sold a session that fits their hours and reported separately. ATP core fans are a retention and upgrade audience; broad casual audiences are deferred.'}], {x:lx, y, w:lw, h:1.05, fontSize:9.8, lineSpacingMultiple:1.06}); y+=1.1;
  sectionLabel(s, lx, y, lw, 'Connected actions'); y+=0.3;
  text(s, [{text:'A public credit ladder ', options:{bold:true}},{text:'(session ₹19-₹39, tournament ₹79-₹99, Finish-the-Season ₹199), each rung credited to the next within 30 days; '},{text:'a morning-replay journey ', options:{bold:true}},{text:'for overnight sessions (spoiler-free push at 07:00 IST with a 20-minute cut); '},{text:'a Race-to-Turin narrative ', options:{bold:true}},{text:'that gives ordinary weeks a reason; and a '},{text:'season-end bridge ', options:{bold:true}},{text:'into the ₹179 all-sport Monthly Pass and the 2027 season at a ₹349 loyalty price.'}], {x:lx, y, w:lw, h:1.05, fontSize:9.8, lineSpacingMultiple:1.06});
  let ry=2.42; sectionLabel(s, rx, ry, rw, 'Economics of the pilot (modelled)'); ry+=0.32;
  const rows=[['Metric','Downside','Base','Upside'],
    ['Attributed new payers (dedup) / incremental', `${fmt.n(sc('new_payers_attributed_dedup','downside'))} / ${fmt.n(sc('incremental_new_payers','downside'))}`, `${fmt.n(sc('new_payers_attributed_dedup','base'))} / ${fmt.n(sc('incremental_new_payers','base'))}`, `${fmt.n(sc('new_payers_attributed_dedup','upside'))} / ${fmt.n(sc('incremental_new_payers','upside'))}`],
    ['Attributed CAC, scalable paid rows (excl. prospecting test)', fmt.inr(sc('paid_ex_test_cac_attributed','downside')), fmt.inr(sc('paid_ex_test_cac_attributed','base')), fmt.inr(sc('paid_ex_test_cac_attributed','upside'))],
    ['Incremental CAC, all paid rows', fmt.inr(sc('paid_blended_cac_incremental','downside')), fmt.inr(sc('paid_blended_cac_incremental','base')), fmt.inr(sc('paid_blended_cac_incremental','upside'))],
    ['12-month contribution per new payer (before marketing, net of cannibalisation)', fmt.inr(sc('value_per_new_payer_m12','downside')), fmt.inr(sc('value_per_new_payer_m12','base')), fmt.inr(sc('value_per_new_payer_m12','upside'))],
    ['24-month net of the scalable acquisition rows (rights horizon)', fmt.lakh(SC.downside.totals.acq_net.m24), fmt.lakh(SC.base.totals.acq_net.m24), fmt.lakh(SC.upside.totals.acq_net.m24)],
    ['12-month net of the whole ₹10 lakh programme', fmt.lakh(SC.downside.totals.net.m12), fmt.lakh(SC.base.totals.net.m12), fmt.lakh(SC.upside.totals.net.m12)]];
  const th = table(s, rows, {x:rx, y:ry, colW:[3.05,1.06,1.06,1.06], fontSize:9}); ry+=th+0.12; fit('exec table', th, 2.3);
  sectionLabel(s, rx, ry, rw, 'What FanCode should approve and test next'); ry+=0.3;
  text(s, [{text:'Approve ₹10 lakh of marketing for nine weeks plus about ₹4 lakh of one-off implementation (spoiler-free replay surfaces, credit-ladder checkout).', options:{bullet:true, breakLine:true}},
           {text:'Measure with a persistent 10% holdout and a geo/time crossover, so marketing-caused new payers are counted against organic demand, never by last click.', options:{bullet:true, breakLine:true}},
           {text:'Gates: attributed CAC ≤ ₹200 and CRM lift ≥ 30% at day 45; next-event return ≥ 45% and upgrade share ≥ 20% at day 90; pass both, then scale search/retargeting and CRM for the Feb-Mar 2027 wave.', options:{bullet:true}}], {x:rx, y:ry, w:rw, h:6.48-ry, fontSize:9.2, paraSpaceAfter:2, lineSpacingMultiple:1.02});
  fit('exec bullets', 1.3, 6.48-ry);
  takeaway(s, 'Forecasts are modelled outputs of the cohort and channel model, not observed results; thresholds are proposed test targets. Contribution excludes the fixed ATP rights fee, so it is not profit. The same prices, budget, CAC definitions and horizons run through Solutions 1-8.');
}
// ------------------------------------------------------------------ 3 SOLUTION 1
{ const s = pres.addSlide();
  frame(s, {title:[{t:'ATP adds paid growth where intent is observable: '},{t:'ordinary weeks are a retention audience, marquee weeks are the acquisition window', a:true}], tag:'Solution 1 of 8', sub:'Commercial diagnosis and audience priorities', page:3,
    sources:'Sources: CF1-CF6, CF9, CF15 (case brief); S3 ATP calendar; S15 LaLiga on FanCode; IST conversions in research/calendar_ist.csv (typical session times; confirm against the 2026 order of play). Contribution: ₹89 ÷ 1.18 GST, less 4% gateway and support and ₹2 per streaming hour (assumptions). Assignment uses first-party consented data only; no Dream11 data sharing is assumed; adjacent-sport rows are cross-sell of existing payers and never enter the new-payer count.'});
  const lx=MX, lw=3.85; let y=1.28;
  sectionLabel(s, lx, y, lw, 'What the brief fixes'); y+=0.32;
  s.addChart(pres.ChartType.bar, [{name:'Viewership index', labels:['Ordinary ATP week','India-friendly Masters week'], values:[100,150]}], {x:lx, y, w:lw, h:1.4, barDir:'col', chartColors:[T.blue], showValue:true, dataLabelPosition:'outEnd', dataLabelFontSize:9, dataLabelColor:T.dark, dataLabelFontFace:F.body, catAxisLabelFontSize:8.5, catAxisLabelColor:T.grey, catAxisLabelFontFace:F.body, valAxisHidden:true, valGridLine:{style:'none'}, catGridLine:{style:'none'}, showLegend:false, showTitle:true, title:'Viewership index (case: ~50% uplift, CF3)', titleFontSize:9, titleColor:T.grey, titleFontFace:F.body, valAxisMaxVal:190, valAxisMinVal:0, barGapWidthPct:70});
  y+=1.5;
  const call=(yy,big,small,col)=>{ rect(s, lx, yy, lw, 0.84, {fill:T.neutral, round:true, r:0.06}); text(s, big, {x:lx+0.12, y:yy+0.06, w:lw-0.24, h:0.28, fontFace:F.head, bold:true, fontSize:11.5, color:col||T.deep, valign:'middle'}); text(s, small, {x:lx+0.12, y:yy+0.36, w:lw-0.24, h:0.48, fontSize:8.6, color:T.grey}); };
  call(y, '~90% of ordinary-week viewers are fans', 'Only ~10% of ordinary-week ATP viewers are non-fans (CF4): ordinary weeks are for retention and upgrades, not mass acquisition.'); y+=0.92;
  call(y, `₹89 pass earns ~₹${r0(U.c_t89)} vs ₹150-₹200 CAC`, 'A Masters tournament pass alone cannot repay acquisition; later paid decisions must (Solution 4).', T.orange); y+=0.92;
  call(y, '17:00 IST vs 00:00-01:00 IST', 'Shanghai night sessions start at 17:00 IST; Vienna, Paris and Turin evenings at 00:00-01:00 IST (S3, IST conversion). Player appeal and ability to watch live differ.'); y+=0.92;
  call(y, '240M registered is not a tennis audience', 'Registered users (CF1) are not viewers or prospects; no addressable-audience arithmetic is used.');
  const rx=4.4, rw=8.58; sectionLabel(s, rx, 1.28, rw, 'Audience priority matrix: one segment per user; the highest tennis signal wins (P1 to P6)');
  const rows=[['Segment','Observable signal (lookback)','Pays today → incremental action sought','Barrier','Objective','Priority'],
   [{text:'P1  ATP core followers', options:{bold:true}}, '≥2 ATP events watched or ≥2 passes bought in 2026, or a 2025 season pass (365 days)', 'Mostly paying → season upgrade, 2027 renewal', 'Fatigue; no reason to pay more', 'Retain, upgrade, renew; no paid media', {text:'Retain', options:{bold:true, color:T.deep}}],
   [{text:'P2  Marquee- or Slam-led followers', options:{bold:true}}, 'One 2026 Masters pass and no repeat; ≥2 tennis highlight views in a marquee week; tennis-page visits (90 days); lapsed 2025 buyers', 'Free or lapsed → first FanCode payment (new payer)', 'Ordinary weeks feel irrelevant; 00:00-01:00 IST starts', 'Acquire first, move up the ladder', {text:'1', options:{bold:true, color:T.orange}}],
   [{text:'P3  F1 viewers', options:{bold:true}}, 'F1 pass holder, ≥3 race weekends watched this season', 'Existing payer → first ATP purchase (not a new payer)', 'Sunday clash with races; no tennis habit', 'Cross-sell weekday night sessions', {text:'2', options:{bold:true, color:T.orange}}],
   [{text:'P4  MotoGP viewers', options:{bold:true}}, 'MotoGP pass holder; watches morning-IST Asia-Pacific rounds', 'Existing payer → first ATP purchase', 'Small pool; different hours from F1', 'Cross-sell Asian-swing mornings', {text:'3', options:{bold:true, color:T.orange}}],
   [{text:'P5  Football (LaLiga) late-night viewers', options:{bold:true}}, '≥2 LaLiga matches starting after 23:30 IST watched (60 days)', 'Existing payer → first ATP purchase', 'No presumed tennis interest: test only', 'Cross-sell European evening sessions', {text:'3 (test)', options:{bold:true, color:T.orange}}],
   [{text:'P6  Broad casual, cricket-only', options:{bold:true}}, 'No tennis signal (most of the 240M registered)', 'Free → new payer', 'Low intent; CAC far above target', 'Defer until lift is proven', {text:'Defer', options:{bold:true, color:T.grey}}]];
  const th = table(s, rows, {x:rx, y:1.62, colW:[1.42,2.3,1.75,1.25,1.15,0.71], fontSize:9.5, zebra:true}); fit('S1 matrix', th, 4.6);
  takeaway(s, 'First cohorts: P2 (new payers with observable tennis intent) and Finish-the-Season buyers in marquee weeks. P1 is a retention and upgrade opportunity, adjacent-sport payers are cross-sell, P6 is deferred. No segment populations are estimated; the plan is budget-normalised.');
}
// ------------------------------------------------------------------ 4 SOLUTION 2
{ const s = pres.addSlide();
  frame(s, {title:[{t:'Each persona gets its own trigger, offer and window: '},{t:'paid spend concentrates at T-48h, owned channels build the occasion earlier', a:true}], tag:'Solution 2 of 8', sub:'Persona-specific campaigns across the calendar', page:4,
    sources:'Sources: CF6, CF11 (case brief); S3 ATP 2026 calendar; IST session windows are typical of recent editions (research/calendar_ist.csv), confirm against the 2026 order of play. Copy is original and subject to normal commercial approval; no player participation is promised.'});
  const weeks=[['23-29 Sep','Chengdu / Hangzhou','ATP 250','10:00 IST','ord'],['30 Sep-6 Oct','Tokyo / Beijing','ATP 500','07:30 & 17:00 IST','mid'],['7-18 Oct','Shanghai Masters (12 days)','M1000','10:00 & 17:00 IST','mq'],['19-25 Oct','Almaty / Brussels / Lyon','ATP 250','12:30-23:00 IST','ord'],['26 Oct-1 Nov','Basel / Vienna','ATP 500','18:00 & 00:00 IST','mid'],['2-8 Nov','Paris Masters','M1000','15:30 & 00:00 IST','mq'],['8-14 Nov','Stockholm','ATP 250','16:30 & 23:00 IST','ord'],['15-22 Nov','Nitto ATP Finals, Turin','Finals','18:30 & 01:00 IST','mq']];
  sectionLabel(s, MX, 1.26, W-2*MX, 'Pilot calendar, 23 Sep-22 Nov 2026 (S3): blue weeks carry paid acquisition, other weeks are owned-channel only');
  const cw=(W-2*MX-7*0.06)/8; let x=MX; const cy=1.58;
  weeks.forEach(w=>{ const mq=w[4]==='mq'; rect(s, x, cy, cw, 0.82, {fill: mq? T.deep : (w[4]==='mid'? T.pale : T.neutral), round:true, r:0.05});
    text(s, w[0], {x:x+0.07, y:cy+0.04, w:cw-0.14, h:0.2, fontSize:8, bold:true, color: mq? 'CFE3FA' : T.grey});
    text(s, w[1], {x:x+0.07, y:cy+0.23, w:cw-0.14, h:0.32, fontFace:F.head, bold:true, fontSize:8.5, color: mq? T.white : T.dark});
    text(s, w[2]+' · '+w[3], {x:x+0.07, y:cy+0.55, w:cw-0.14, h:0.24, fontSize:7.5, color: mq? 'CFE3FA' : (/00:00|01:00|23:00/.test(w[3])? T.orange : T.grey)}); x+=cw+0.06; });
  text(s, 'Orange = overnight starts, sold as a morning-replay occasion, not chased with live-conversion spend.  Paid conversion: T-48h to match start (CF11).  Owned and editorial build: from T-7 days.  Retention: from the first view.', {x:MX, y:2.44, w:W-2*MX, h:0.22, fontSize:8, color:T.grey});
  const rows=[['Persona','Trigger and window (IST)','Offer → intended next paid action','Sample message (original)','Channel · suppression · frequency cap','Activation KPI · retained-payer KPI'],
   [{text:'P2 Marquee-led, free or lapsed', options:{bold:true}}, 'T-48h before Shanghai first round (Mon 5 Oct for Wed 7 Oct); 07:00 IST replay push after overnight Paris and Turin sessions', '₹89 Shanghai pass → credit toward ₹199 Finish-the-Season within 30 days', {text:'"Shanghai starts Wednesday, 17:00 IST. ₹89 covers all 12 days, and counts toward the rest of the season if you upgrade by 6 Nov."', options:{color:T.orange}}, 'Search + retargeting (paid), push (owned); suppress on purchase; 3 pushes/week', 'First purchase rate; upgrade within 30 days; D90 retained payer'],
   [{text:'P1 ATP core (paying)', options:{bold:true}}, 'Sunday night after each tournament final; day 20 of the 30-day credit window', 'Upgrade to Finish-the-Season ₹199 (credit applied); 2027 loyalty price ₹349 by 15 Jan', '"Vienna is done, Paris starts Monday. Three Turin places are still open. Your ₹79 Vienna pass takes ₹79 off the rest of the season."', 'Push/email only, no paid media; 2 messages/week', 'Next-event return; upgrade share; 2027 renewal (eligible cohort)'],
   [{text:'P3 F1 pass holders (existing payers)', options:{bold:true}}, 'Tuesday-Friday after an F1 weekend; never on race Sunday', '₹29-₹39 India-friendly night session → session price credited to the tournament pass', '"No race until Sunday. Tonight\'s Shanghai night session starts 17:00 IST, ₹29, replay included."', 'In-app + push; suppress if any ATP entitlement is active; 2/week', 'First ATP purchase (reported apart from new payers); ladder step'],
   [{text:'P4 MotoGP pass holders (existing payers)', options:{bold:true}}, 'Saturday and Sunday mornings in the Asian swing (Tokyo 07:30, Shanghai 10:00 IST)', '₹29 day-session pass → tournament credit', '"You\'re up early for MotoGP anyway. Shanghai day session from 10:00 IST, ₹29."', 'Push; 1/week', 'First ATP purchase; morning-session views'],
   [{text:'P5 LaLiga late-night viewers (existing payers)', options:{bold:true}}, 'Friday and Saturday late night in the Vienna, Paris and Turin weeks', '₹19-₹29 evening session with the 07:00 IST spoiler-free replay', {text:'"Kick-off is at 1:30 AM and so is the Paris evening session. ₹29: watch it live, or spoiler-free at 7 AM."', options:{color:T.orange}}, 'In-app; 1/week; stop after 2 unopened pushes', 'First ATP purchase; replay opens; refunds < 2%']];
  const th = table(s, rows, {x:MX, y:2.72, colW:[1.35,2.2,2.05,3.0,2.2,1.83], fontSize:8.7, zebra:true}); fit('S2 table', th, 3.15);
  const by=2.72+th+0.1; rect(s, MX, by, W-2*MX, 6.5-by, {fill:T.neutral, round:true, r:0.06});
  text(s, [{text:'Marquee week (Shanghai, 7-18 Oct): ', options:{bold:true, color:T.deep}},{text:'paid search and retargeting at T-48h, a contest with pass prizes, ESPN.in takeover in test cities, CRM to all personas, editorial preview.   '},{text:'Ordinary week (Almaty/Brussels/Lyon, 19-25 Oct): ', options:{bold:true, color:T.deep}},{text:'no paid acquisition; Race-to-Turin update, ₹19 session passes for followed players (P3-P5), upgrade-credit reminders to P1 and P2, morning replays for the 23:00 IST Brussels evening session.'}], {x:MX+0.12, y:by+0.03, w:W-2*MX-0.24, h:6.5-by-0.06, fontSize:8.4, valign:'middle', lineSpacingMultiple:1.0});
  fit('S2 exec box', 0.5, 6.5-by);
  takeaway(s, 'Differentiation sits in timing and entitlement state, not only in creative: new payers get the tournament-to-season ladder; adjacent-sport payers get a ₹19-₹39 session that fits their hours. T-48h paid spend converts an occasion that owned channels and editorial have already built.');
}
// ------------------------------------------------------------------ 5 SOLUTION 3
{ const s = pres.addSlide();
  frame(s, {title:[{t:'A public three-rung ladder (session, tournament, Finish-the-Season): '},{t:'each rung is credited to the next, so the top price is never undercut', a:true}], tag:'Solution 3 of 8', sub:'Offer architecture and competitor positioning', page:5,
    sources:'Sources: CF8, CF15, CF16 (case); S5 JioHotstar press release (new-subscriber prices from 28 Jan 2026); S6 SonyLIV help centre; S7-S8 Tennis TV help centre and App Store India in-app listing; S10-S11 FanCode subscription page and terms; S12 ITD posts. Tennis TV live availability in India under FanCode exclusivity is not verified. Secondary equivalent-monthly view: Finish-the-Season ≈ ₹124 a month over 1.6 months, JioHotstar Mobile annual ≈ ₹42 a month, Tennis TV annual ≈ ₹375 a month; entertainment bundles are not ATP substitutes. Cost assumptions: 18% GST, 4% gateway and support, ₹2 per streaming hour.'});
  const lx=MX, lw=7.75; sectionLabel(s, lx, 1.26, lw, 'Rate card: existing products in grey, proposed tests in orange');
  const ex=(t)=>({text:t, options:{color:T.grey, bold:true}}), pr=(t)=>({text:t, options:{color:T.orange, bold:true}});
  const rows=[['SKU','Price','Validity and content','Target','Upgrade treatment','Restriction'],
   [pr('Session pass (proposed)'), '₹39 / ₹29 Masters and Finals (India-friendly / overnight); ₹29 / ₹19 ATP 500; ₹19 ATP 250', 'One session; live + 48h replay, spoiler-free morning cut', 'P3-P5 existing payers; P2 in overnight weeks', 'Full price credited to that tournament\'s pass until its final', 'Max 3 per tournament per account; floor ₹19'],
   [ex('Tournament pass (existing, case ₹79-₹99)'), '₹79 ATP 250/500; ₹89 Masters 1000; ₹99 ATP Finals', 'Whole event, live + replays', 'P2 new payers; P1 repeaters', 'Full price (cap ₹99, one per account) credited to Finish-the-Season within 30 days', 'No stacking with promos; floor ₹59'],
   [pr('Finish-the-Season pass (proposed)'), '₹199', '5 Oct-22 Nov: Shanghai, all 250s, Basel/Vienna, Paris, ATP Finals, weekly show, replays', 'Marquee-week paid media; upgraders', '2027 season at the ₹349 loyalty price by 15 Jan (a price, not a credit)', 'Only 3+ event buyers save; floor ₹149'],
   [ex('ATP Season Pass 2027 (existing ₹399)'), '₹399 list; ₹349 loyalty', 'Calendar year 2027, all 56 events; not all-sport', 'Renewers; January direct buyers', 'Public rate card declines with remaining season value (proposed)', 'Floor ₹249'],
   [ex('Monthly Pass, all sports (existing)'), '₹179 (₹199 struck, S10)', 'All paywalled sports for a month, ATP included', 'Season-end bridge for ATP-only holders', 'Sold as a new entitlement on 23 Nov', 'Holder watching ATP is not a new payer']];
  const th = table(s, rows, {x:lx, y:1.58, colW:[1.25,1.5,1.62,1.08,1.35,0.95], fontSize:8.2, zebra:true}); fit('S3 rate card', th, 3.45);
  let y=1.58+th+0.1; rect(s, lx, y, lw, 6.48-y, {fill:T.neutral, round:true, r:0.06});
  text(s, [{text:'Rules. ', options:{bold:true, color:T.deep}},{text:'One price reduction per checkout: upgrade credit > segment offer > public promo. Arbitrage: three ₹19 sessions (₹57) undercut only the ₹79 ATP 250 pass, so sessions are capped at three per tournament; two tournament passes (₹158-₹178) cost less than ₹199, so only three-or-more event buyers gain. '},
           {text:'Schedule changes. ', options:{bold:true, color:T.deep}},{text:'Cancelled session or walkover before start: automatic session credit (refund on request); abandoned event: pro-rata credit; no SKU promises a named player. '},
           {text:'Rejected. ', options:{bold:true, color:T.deep}},{text:'A ₹19 replay rental (₹10 below the session pass, a fourth checkout choice; replay is folded into the session pass) and a player bundle (participation cannot be guaranteed; events define bundles, players the narrative).'}], {x:lx+0.12, y:y+0.04, w:lw-0.24, h:6.48-y-0.08, fontSize:8.2, valign:'top', lineSpacingMultiple:1.02});
  fit('S3 rules box', 0.95, 6.48-y);
  const rx=8.3, rw=4.68; sectionLabel(s, rx, 1.26, rw, 'Two timing examples and one upgrade checkout');
  rect(s, rx, 1.58, rw, 0.98, {fill:T.pale, round:true, r:0.06});
  text(s, [{text:'India-friendly Masters session: ', options:{bold:true, color:T.deep}},{text:'Shanghai night session, Wed 14 Oct, 17:00 IST: ₹39 session · ₹89 tournament · ₹199 Finish-the-Season.', options:{breakLine:true}},
           {text:'Overnight ATP 500 session: ', options:{bold:true, color:T.deep}},{text:'Vienna evening session, Thu 29 Oct, 00:00 IST: ₹19 session with the 07:00 IST spoiler-free replay · ₹79 tournament · ₹199 Finish-the-Season.'}], {x:rx+0.1, y:1.61, w:rw-0.2, h:0.92, fontSize:8.6, valign:'middle', paraSpaceAfter:3});
  rect(s, rx, 2.64, rw, 0.74, {fill:T.paleOrange, round:true, r:0.06});
  text(s, [{text:'Upgrade example: ', options:{bold:true, color:T.orange}},{text:`Shanghai pass bought 7 Oct for ₹89; upgrade to Finish-the-Season by 6 Nov: pay ₹110 (₹199 − ₹89 credit). Total paid ₹199, the same as a direct buyer; the credit is a price reduction, never revenue. Contribution of the step: ~₹${r0(U.c_step_t_fts)}.`}], {x:rx+0.1, y:2.67, w:rw-0.2, h:0.68, fontSize:8.6, valign:'middle'});
  sectionLabel(s, rx, 3.4, rw, 'Competitor panel: out-of-pocket INR and scope');
  const crow=[['Product','Out-of-pocket (INR)','Period and scope'],
   ['FanCode tournament pass (existing)','₹79-₹99','One ATP event, live + replays (CF15)'],
   [{text:'FanCode Finish-the-Season (proposed)', options:{color:T.orange, bold:true}},'₹199','5 Oct-22 Nov 2026, all remaining ATP events'],
   ['FanCode Monthly Pass','₹179 a month','All paywalled sports incl. ATP (S10, S11)'],
   ['JioHotstar Mobile / Super','₹79 / ₹149 a month; ₹499 / ₹1,099 a year','1 or 2 devices, ads; no ATP Tour (S5)'],
   ['SonyLIV Mobile Only / Premium','₹699 a year; ₹399 a month or ₹1,499 a year','720p or up to 4K; live sports; no ATP Tour (S6)'],
   ['Tennis TV (ATP\'s own service)','₹449 a month; ₹4,499 a year (App Store India)','ATP-only, no Slams; India availability under FanCode exclusivity unverified (S7, S8)']];
  const ch = table(s, crow, {x:rx, y:3.7, colW:[1.45,1.55,1.68], fontSize:7.8, zebra:true}); fit('S3 competitor', ch, 2.35);
  fit('S3 competitor end', 3.7+ch, 6.5);
  takeaway(s, 'The price buys a defined scope: one session, one event, or the rest of the season. Credits keep the ladder arbitrage-safe (no path to Finish-the-Season costs less than ₹199) and protect value: only three-or-more event buyers, the habit we want, pay less than before.');
}
// ------------------------------------------------------------------ 6 SOLUTION 4
{ const s = pres.addSlide();
  frame(s, {title:[{t:'₹150-₹200 CAC pays back only for Finish-the-Season or owned-channel entrants; '},{t:`tournament-pass entrants need a ${fmt.pct(be.be_upgrade_m24_cac183)} upgrade share`, a:true}], tag:'Solution 4 of 8', sub:'Cohort contribution and break-even economics', page:6,
    sources:`Sources: CF7-CF9, CF15, CF16, CF18. Assumptions: prices GST-inclusive (18%); 4% of gross for gateway and support; ₹2 per streaming hour; pathway mix 40/40/20 (repeat + upgrade = 60%, CF8 lower bound); repeaters buy 1.5 more passes in 12 months and 2.5 in 24; 2027 loyalty renewal 35% (upgraders) / 60% (direct FTS); 90% of 2027 renewers renew for 2028 (CF7, once-renewed customers only). Downside/upside vary CVR ×0.7/×1.3, upgrade share 10%/30%, repeats ×0.8/×1.2, incrementality ×0.75/×1.25, costs +20%/−10%, cannibalisation ×1.5/×0.5, renewals 25-40%/50-75%. Horizons run from a 7 Oct 2026 purchase.`});
  const lx=MX, lw=6.75; sectionLabel(s, lx, 1.26, lw, 'Contribution before marketing per customer pathway (₹, base case, modelled)');
  const h=(k)=>[fmt.inr(P[k].d90), fmt.inr(P[k].m12), fmt.inr(P[k].m24)];
  const rows=[['Pathway (entry SKU; branches are mutually exclusive)','90 days','12 months','24 months (rights horizon)','Affordable CAC 12m / 24m'],
   ['1. Entry-only: ₹89 Masters pass, never returns', ...h('entry_only'), `${fmt.inr(P.entry_only.m12)} / ${fmt.inr(P.entry_only.m24)}`],
   ['2. Repeat tournament buyer, no upgrade (1.5 / 2.5 more passes)', ...h('repeat_no_upgrade'), `${fmt.inr(P.repeat_no_upgrade.m12)} / ${fmt.inr(P.repeat_no_upgrade.m24)}`],
   ['3. Upgrade via credit: ₹89 + ₹110 to Finish-the-Season, then loyalty renewal', ...h('upgrade_via_credit'), `${fmt.inr(P.upgrade_via_credit.m12)} / ${fmt.inr(P.upgrade_via_credit.m24)}`],
   ['4. Direct Finish-the-Season buyer (₹199), then loyalty renewal', ...h('fts_direct'), `${fmt.inr(P.fts_direct.m12)} / ${fmt.inr(P.fts_direct.m24)}`],
   [{text:'Expected tournament-pass entrant (40% / 40% / 20% mix of 1-3)', options:{bold:true}}, {text:fmt.inr(Et.d90), options:{bold:true}}, {text:fmt.inr(Et.m12), options:{bold:true}}, {text:fmt.inr(Et.m24), options:{bold:true}}, {text:`${fmt.inr(Et.m12)} / ${fmt.inr(Et.m24)}`, options:{bold:true, color:T.orange}}],
   ['Expected session entrant (₹29 blended: 45% never return, 25% repeat, 30% step up)', fmt.inr(Es.d90), fmt.inr(Es.m12), fmt.inr(Es.m24), `${fmt.inr(Es.m12)} / ${fmt.inr(Es.m24)}`]];
  const th = table(s, rows, {x:lx, y:1.58, colW:[2.95,0.8,0.9,1.1,1.0], fontSize:8.8, zebra:true}); fit('S4 pathways', th, 3.0);
  let y=1.58+th+0.1; rect(s, lx, y, lw, 6.48-y, {fill:T.neutral, round:true, r:0.06});
  text(s, [{text:'How to read it. ', options:{bold:true, color:T.deep}},{text:`Contribution = price ÷ 1.18 − 4% of gross − ₹2 per streaming hour; the ATP rights fee is fixed and confidential, so this is contribution, not profit. A ₹89 pass earns ₹${r0(U.c_t89)}, the ₹110 upgrade step ₹${r0(U.c_step_t_fts)}, a ₹349 loyalty renewal ₹${r0(U.c_season349)}; the season-end Monthly Pass bridge adds about ₹${r0(U.xsport_value)} per Finish-the-Season holder (inside pathways 3 and 4). Repeat purchases and upgrades are never both counted for one customer; existing subscribers are not new acquisition revenue.  `},
           {text:'Break-even upgrade share ', options:{bold:true, color:T.deep}},{text:`u* = (CAC − C_entry) ÷ (C_upgrade − C_entry), entry path = 50/50 mix of pathways 1 and 2. At the ₹${c2cac} search/retargeting CAC: ${fmt.pct(be.be_upgrade_m12_cac183)} within 12 months (not achievable), ${fmt.pct(be.be_upgrade_m24_cac183)} within 24 months (base 20%, ladder target 30%); ${fmt.pct(be.be_upgrade_m24_cac150)} at ₹150 and ${fmt.pct(be.be_upgrade_m24_cac200)} at ₹200 over 24 months.`}], {x:lx+0.12, y:y+0.05, w:lw-0.24, h:6.48-y-0.1, fontSize:8.5, lineSpacingMultiple:1.04});
  fit('S4 read box', 1.3, 6.48-y);
  const rx=7.3, rw=5.68; sectionLabel(s, rx, 1.26, rw, 'Downside / base / upside (modelled)');
  const srows=[['Metric','Downside','Base','Upside'],
   ['Attributed new payers (dedup)', fmt.n(sc('new_payers_attributed_dedup','downside')), fmt.n(sc('new_payers_attributed_dedup','base')), fmt.n(sc('new_payers_attributed_dedup','upside'))],
   ['Attributed CAC, scalable paid rows', fmt.inr(sc('paid_ex_test_cac_attributed','downside')), fmt.inr(sc('paid_ex_test_cac_attributed','base')), fmt.inr(sc('paid_ex_test_cac_attributed','upside'))],
   ['Incremental CAC, all paid rows', fmt.inr(sc('paid_blended_cac_incremental','downside')), fmt.inr(sc('paid_blended_cac_incremental','base')), fmt.inr(sc('paid_blended_cac_incremental','upside'))],
   ['12-month contribution per new payer', fmt.inr(sc('value_per_new_payer_m12','downside')), fmt.inr(sc('value_per_new_payer_m12','base')), fmt.inr(sc('value_per_new_payer_m12','upside'))],
   ['Cannibalisation cost, 12 months', fmt.lakh(SC.downside.totals.cannibalisation.m12), fmt.lakh(SC.base.totals.cannibalisation.m12), fmt.lakh(SC.upside.totals.cannibalisation.m12)],
   ['24-month net, scalable acquisition rows', fmt.lakh(SC.downside.totals.acq_net.m24), fmt.lakh(SC.base.totals.acq_net.m24), fmt.lakh(SC.upside.totals.acq_net.m24)],
   ['12 / 24-month net, whole ₹10 lakh programme', `${fmt.lakh(SC.downside.totals.net.m12)} / ${fmt.lakh(SC.downside.totals.net.m24)}`, `${fmt.lakh(SC.base.totals.net.m12)} / ${fmt.lakh(SC.base.totals.net.m24)}`, `${fmt.lakh(SC.upside.totals.net.m12)} / ${fmt.lakh(SC.upside.totals.net.m24)}`]];
  const sh = table(s, srows, {x:rx, y:1.58, colW:[2.0,1.25,1.15,1.28], fontSize:8.5, zebra:true}); fit('S4 scenarios', sh, 2.6);
  let sy=1.58+sh+0.14; sectionLabel(s, rx, sy, rw, `24-month value of a tournament entrant (₹); green ≥ ₹${c2cac} CAC`); sy+=0.3;
  const sens=M.sensitivity; const ups=[0.1,0.2,0.3,0.4], reps=[1.5,2.5,3.5];
  const grid=[['Upgrade share ↓ / repeat passes in 24 months →', ...reps.map(r=>String(r))]];
  ups.forEach(u=>{ grid.push([fmt.pct(u), ...reps.map(rp=>{ const v=sens.find(x=>Math.abs(x.upgrade_share-u)<1e-9 && Math.abs(x.repeat_passes_24m-rp)<1e-6).value_m24; return {text:fmt.inr(v), options:{fill:{color: v>=c2cac? T.paleGreen : T.paleRed}, align:'center'}}; })]); });
  const gh = table(s, grid, {x:rx, y:sy, colW:[2.3,1.12,1.13,1.13], fontSize:8.8}); fit('S4 grid', sy+gh, 6.5);
  takeaway(s, `Base case: the pilot loses ${fmt.lakh(SC.base.totals.net.m12).replace('−','')} in 12 months and the scalable rows turn positive (${fmt.lakh(SC.base.totals.acq_net.m24)}) only within the 2028 rights horizon. If the measured upgrade share stays below ~${fmt.pct(be.be_upgrade_m24_cac183)}, stop scaling tournament-pass acquisition and sell only Finish-the-Season and season entries to paid audiences.`);
}
// ------------------------------------------------------------------ 7 SOLUTION 5
{ const s = pres.addSlide();
  frame(s, {title:[{t:'Retention is built around the next occasion: '},{t:'the morning replay, the Race to Turin, the 30-day upgrade window and a season-end bridge', a:true}], tag:'Solution 5 of 8', sub:'Retention across tournaments and other sports', page:7,
    sources:'Sources: CF6, CF7, CF17 (case); S3 calendar (Next Gen ATP Finals date TBD; 2027 season opens 5 Jan; the Australian Open, 18 Jan-1 Feb, is not a FanCode right); S9 spoiler control is an existing pattern in the ATP\'s own service; S10-S11 Monthly Pass scope; S13 existing weekly show; S15 LaLiga on FanCode. Costs: editorial in Solution 6 row C5, engineering in the ₹4 lakh implementation budget.'});
  const rows=[['Lane','Onboarding (day 0)','After the first view (days 0-2)','Before the next event (T-72h to T-24h)','Ordinary week','Expiry / season end (22 Nov)','Renewal / next season (Dec-Jan)'],
   [{text:'Customer trigger', options:{bold:true}}, 'First purchase (any rung)', 'Live session watched, or overnight session missed', 'Tournament ends; followed player\'s next draw is out', 'No marquee event; ATP 250 week', 'Finish-the-Season or season entitlement expires', '2027 season opens 5 Jan; no Slam rights 18 Jan-1 Feb; Feb 500s from 9 Feb'],
   [{text:'FanCode action (owner)', options:{bold:true}}, 'Pick 2 players and a viewing window (live / morning); spoiler preference; IST schedule for the event (CRM)', '07:00 IST spoiler-free push with full replay and 20-minute cut, only for overnight sessions, suppressed if watched live (Product, Editorial)', 'Race-to-Turin update: standings, next event\'s IST windows, day-20 credit reminder, one-tap upgrade (Editorial, CRM)', 'Weekly show + ₹19 session for the followed player\'s match; no paid media; nothing sent if the player is out (Editorial)', 'Season recap; Monthly Pass ₹179 bridge (F1 finale, MotoGP, LaLiga); Next Gen Finals in December; 2027 loyalty price ₹349 by 15 Jan (CRM, Commercial)', 'Season-start push with the first India-friendly session; Feb 500s as the first paid occasion; win-back for lapsed entrants (CRM)'],
   [{text:'Commercial outcome (measure)', options:{bold:true}}, 'Profile completion; qualified first view ≥ 20 min', '2nd qualified view within the event (behavioural retention)', 'Next-event return; upgrade to Finish-the-Season (commercial retention)', 'Qualified views in ≥ 2 distinct event weeks (behavioural)', 'Cross-sport upgrade: a new ₹179 entitlement, incremental (not free access)', 'Renewal rate among the eligible, matured cohort only']];
  const th = table(s, rows, {x:MX, y:1.28, colW:[1.15,1.78,2.05,2.05,1.75,2.0,1.85], fontSize:8.8}); fit('S5 swimlane', th, 3.2);
  let y=1.28+th+0.14; const cw3=(W-2*MX-0.3)/3; const bh=6.48-y;
  const box=(x,title,body,col)=>{ rect(s, x, y, cw3, bh, {fill: col||T.neutral, round:true, r:0.06}); text(s, title, {x:x+0.12, y:y+0.07, w:cw3-0.24, h:0.26, fontFace:F.head, bold:true, fontSize:9.5, color:T.deep}); text(s, body, {x:x+0.12, y:y+0.36, w:cw3-0.24, h:bh-0.4, fontSize:9.4, lineSpacingMultiple:1.08}); };
  box(MX, 'Bridge 1: ATP to the rest of the portfolio', 'Verified access rule: an ATP tournament or Finish-the-Season pass gives no F1, MotoGP or LaLiga access. The Monthly Pass (₹179, S10) covers all paywalled sports for a month (S11), so the season-end offer on 23 Nov is a new, incremental entitlement, not a free benefit. A Monthly or Yearly holder who watches ATP is an engagement outcome, never a new ATP payer. Suppression: no bridge offer to anyone already holding a Monthly or Yearly pass.');
  box(MX+cw3+0.15, 'Bridge 2: the rest of the portfolio to ATP (existing payers)', 'LaLiga late-night viewers get the Paris and Turin evening sessions (00:00-01:00 IST) with the morning replay; F1 holders get Tuesday-to-Friday night sessions, never race Sunday; MotoGP holders get Asian-swing morning sessions. Each is a first ATP purchase by an existing payer, reported apart from new payers, and each rung is credited toward the next. Entitlement is checked before every send: no offer to a user who already holds ATP access.');
  box(MX+2*(cw3+0.15), 'Controls, off-season and the three retention definitions', 'Caps: 3 pushes a week for new payers, 2 otherwise, 1 replay push a day; opt-out honoured platform-wide; a refund suppresses offers for 30 days. Off-season (23 Nov-4 Jan): Next Gen Finals (date TBD), "best of 2026" replays, no invented live tennis. Behavioural retention = repeat qualified viewing across distinct weeks; commercial retention = a paid ATP entitlement active in the window; renewal = repurchase after expiry, reported only for eligible matured cohorts.', T.pale);
  fit('S5 boxes', 1.7, bh);
  takeaway(s, 'The morning replay and the Race to Turin create the next occasion; the upgrade credit is the next paid decision. Outcomes: next-event return and the day-90 retained-payer rate, reported only for cohorts observed for 90 days. A still-valid pass proves nothing alone: entitlement and qualified viewing are reported together.');
}
// ------------------------------------------------------------------ 8 SOLUTION 6
{ const s = pres.addSlide();
  frame(s, {title:[{t:'A ₹10 lakh pilot at a 52% performance share: '},{t:`${fmt.inr(B.paid_ex_test_cac_attributed)} attributed CAC on the scalable rows; prospecting must earn its place`, a:true}], tag:'Solution 6 of 8', sub:'Marketing investment and channel CAC', page:8,
    sources:`Sources: CF9-CF13 (case). Method per paid row: impressions = spend ÷ CPM × 1000; clicks = impressions × CTR; purchases = clicks × conversion; new payers = purchases × new-payer share; incremental = new payers × validated incremental share. Owned row per 100k eligible: 90% delivered × 5% click × 8% buy. Dedup: 8% of CRM and contest new payers removed as already in retargeting audiences. Blended CAC = spend ÷ deduplicated new payers (harmonic check on paid rows: ₹${r0(B.harmonic_check_paid)}). Planning pools (P2-free 150k, F1 120k, MotoGP 40k, LaLiga 60k) are assumptions replaced by CRM counts on day 0; totals scale linearly.`});
  const rows=[['Row','Share','₹','Persona','Execution and estimation basis','New payers (base)','CAC attributed / incremental','Evidence','Scale / stop rule']];
  const C = M.channels; const lakh=(x)=>'₹'+(x/1e5).toFixed(1)+'L';
  const est={C1:'Meta/YouTube video, FTS ₹199 in marquee weeks; CPM ₹120 × CTR 0.7% × CVR 1.5% × 80% new; geo-split', C2:'Search on tennis/live terms; retargeting of tennis-page visitors; CPC ₹7 × CVR 4.5% × 85% new; control IDs excluded', C3:'Segment pushes at T-48h and 07:00 IST; per 100k eligible: 90% delivered × 5% click × 8% buy; 10% holdout', C4:'3 contests with pass prizes (Shanghai, Paris, Finals); ~9,300 clicks × 7.8% (case CVR) × 55% new', C5:'Race to Turin, 20-minute Morning Match cuts, weekly-show tie-ins; 2 editors on event weeks', C6:'Live in test cities, held out in matched cities; crossover Shanghai/Paris', C7:'Onboarding, replay, pre-event, expiry, season-end messages', C8:'Holdout operations, geo design, dashboards, analyst time'};
  const short={C1:'Prospecting, cold tennis interest (learning test)', C2:'High-intent search + retargeting at T-48h', C3:'First-party CRM: push, email, in-app', C4:'Tennis communities and contests (ITD)', C5:'Editorial and native tennis personalities', C6:'ESPN.in takeover, geo/time-split test', C7:'Retention communications', C8:'Measurement and analytics'};
  const persona={C1:'P2 cold; P6', C2:'P2 new-to-pay', C3:'P2-free new payers; P3-P5 existing payers', C4:'P1/P2 community', C5:'All', C6:'Broad tennis readers', C7:'All payers', C8:'n/a'};
  const evid={C1:'CPM, CTR, CVR assumed; geo readout', C2:'Timing CF11; CPC, CVR assumed', C3:'Pools, rates assumed; holdout readout', C4:'Case CVR 7.8%; CPC assumed', C5:'CF14; cost assumption', C6:'CF13; lift readout', C7:'Cost assumption', C8:'Cost assumption'};
  const rule={C1:'Stop at day 30 unless CAC < ₹300; money to C2', C2:'Scale if ≤ ₹200 attributed and ≤ ₹300 incremental; pause at ₹250', C3:'Keep if measured lift ≥ 30%; else fold into C2', C4:'Continue only if effective CPC ≤ ₹8.6', C5:'Cut if replay opens < 15% with no return lift', C6:'Scale only on positive geo lift', C7:'n/a (cohort KPIs)', C8:'n/a'};
  C.forEach(c=>{ const r=R[c.id]; const np = r.new_payers? (c.id==='C3'? `${fmt.n(r.new_payers)} + ${fmt.n(r.xsell_purchases)} existing-payer ATP purchases` : fmt.n(r.new_payers)) : 'not directly attributed';
    const cac = r.cac_attributed? `${fmt.inr(r.cac_attributed)} / ${fmt.inr(r.cac_incremental)}` : 'not directly attributed';
    rows.push([{text:c.id+'  '+short[c.id], options:{bold:true}}, fmt.pct(c.share), lakh(c.spend), persona[c.id], est[c.id], np, {text:cac, options:{color: r.cac_attributed? (r.cac_attributed<=200? T.green : (r.cac_attributed<=250? T.dark : T.red)) : T.grey, bold:!!r.cac_attributed}}, evid[c.id], rule[c.id]]); });
  rows.push([{text:'Total', options:{bold:true}}, {text:'100%', options:{bold:true}}, {text:'₹10.0L', options:{bold:true}}, '', {text:'Performance rows C1+C2+C4 = 52% (case today 65-70%, CF10); owned 10%; content 25%; retention 6%; measurement 7%', options:{color:T.deep}}, {text:`${fmt.n(B.new_payers_attributed_dedup)} attributed; ${fmt.n(B.incremental_new_payers)} incremental (dedup)`, options:{bold:true}}, {text:`Paid rows ${fmt.inr(B.paid_blended_cac_attributed)} / ${fmt.inr(B.paid_blended_cac_incremental)}; excl. C1 ${fmt.inr(B.paid_ex_test_cac_attributed)} / ${fmt.inr(B.paid_ex_test_cac_incremental)}; programme ${fmt.inr(B.programme_cost_per_new_payer)} per new payer`, options:{bold:true}}, '', {text:'Reallocation rule below', options:{bold:true, color:T.orange}}]);
  const th = table(s, rows, {x:MX, y:1.26, colW:[1.7,0.48,0.55,1.15,2.8,1.35,1.6,1.2,1.8], fontSize:7.6, zebra:true}); fit('S6 plan', th, 3.9);
  let y=1.26+th+0.1; const bw=(W-2*MX-0.3)/3; const bh=6.48-y;
  s.addChart(pres.ChartType.bar, [{name:'Performance share of spend', labels:['Current (case 65-70%, midpoint)','Proposed pilot'], values:[67.5,52]}], {x:MX, y, w:bw, h:bh, barDir:'bar', chartColors:[T.blue], showValue:true, dataLabelFormatCode:'0"%"', dataLabelPosition:'outEnd', dataLabelFontSize:8.5, dataLabelColor:T.dark, dataLabelFontFace:F.body, catAxisLabelFontSize:8, catAxisLabelColor:T.grey, catAxisLabelFontFace:F.body, valAxisHidden:true, valGridLine:{style:'none'}, catGridLine:{style:'none'}, showLegend:false, showTitle:true, title:'Performance share of spend: current vs proposed', titleFontSize:9, titleColor:T.grey, titleFontFace:F.body, valAxisMaxVal:100, valAxisMinVal:0, barGapWidthPct:60});
  rect(s, MX+bw+0.15, y, bw, bh, {fill:T.neutral, round:true, r:0.06});
  const cc=M.contest_cpc_ceilings;
  text(s, [{text:'Contest CPC sanity check (case CVR 7.8%). ', options:{bold:true, color:T.deep}},{text:`₹150-₹200 CAC allows a media CPC of ₹${cc.all_new_payers['150'].toFixed(2)}-₹${cc.all_new_payers['200'].toFixed(2)} only if every buyer is a new payer; at a 55% new-payer share the ceiling is ₹${cc.n055['150'].toFixed(2)}-₹${cc.n055['200'].toFixed(2)}, and on an incremental basis (50% validated) ₹${cc.n055_f05['150'].toFixed(2)}-₹${cc.n055_f05['200'].toFixed(2)}. The planned ₹7.5 clears the attributed ceiling only because prizes are passes, not cash; above ₹8.6, contests stop.`}], {x:MX+bw+0.27, y:y+0.05, w:bw-0.24, h:bh-0.1, fontSize:8, valign:'middle', lineSpacingMultiple:1.02});
  rect(s, MX+2*(bw+0.15), y, bw, bh, {fill:T.paleOrange, round:true, r:0.06});
  text(s, [{text:'Downside exposure and reallocation rule. ', options:{bold:true, color:T.orange}},{text:`Downside attributed CAC on the scalable rows is ${fmt.inr(SC.downside.totals.paid_ex_test_cac_attributed)}, incremental ${fmt.inr(SC.downside.totals.paid_blended_cac_incremental)}: the target is missed. Day 30: stop C1 unless attributed CAC < ₹300. Day 45: move C6 money to C2 only if C2 is ≤ ₹200 attributed and ≤ ₹300 incremental. Pause any paid row above ₹250 attributed; owned rows keep running. CRM conversions are capped by the eligible pool and never rescue a missed paid target.`}], {x:MX+2*(bw+0.15)+0.12, y:y+0.05, w:bw-0.24, h:bh-0.1, fontSize:8, valign:'middle', lineSpacingMultiple:1.02});
  fit('S6 bottom boxes', 0.95, bh);
  takeaway(s, `Commercial result (base, modelled): ${fmt.n(B.new_payers_attributed_dedup)} attributed and ${fmt.n(B.incremental_new_payers)} incremental new payers, ${fmt.inr(B.paid_ex_test_cac_attributed)} attributed CAC on the rows that would scale (${fmt.inr(B.paid_blended_cac_attributed)} with the prospecting test). The allocation change funds measurement and retention; evidence, not preference, returns money to performance.`);
}
// ------------------------------------------------------------------ 9 SOLUTION 7
{ const s = pres.addSlide();
  frame(s, {title:[{t:'Growth is credited to ATP marketing only when a held-out control says so; '},{t:'retention is reported only for matured cohorts', a:true}], tag:'Solution 7 of 8', sub:'Incrementality and sustained-growth scorecard', page:9,
    sources:'Sources: CF9, CF17 (case). Sample sizes: two-sided α = 0.05, power 0.80, normal approximation, per arm; readouts wait until each arm reaches its sample, smaller pools report direction only; retention readouts wait for maturity (day 90 for the September-October cohorts falls between 22 Dec and 16 Jan). Owner: Growth analytics, at days 30, 45, 90 and 120. Qualified view = at least 20 minutes of live, replay or on-demand tennis. D90 = day 90 after first purchase.'});
  const lx=MX, lw=6.3; sectionLabel(s, lx, 1.26, lw, 'Test design: causal impact, not last-click attribution');
  const rows=[['Where','Design','What it separates'],
   [{text:'Owned channels (push, email, in-app)', options:{bold:true}}, '10% persistent user-level holdout for the whole pilot, stratified by payment state, sport affinity (P2-P5), tournament-tier exposure and viewing-window preference; control users receive no ATP CRM on any owned channel', 'Marketing-caused purchases from organic tennis demand, including demand created by F1 and football viewing'],
   [{text:'Paid retargeting', options:{bold:true}}, 'The same control IDs are excluded from retargeting audiences via customer lists; intention-to-treat denominators; unavoidable prospecting spillover is reported, not assumed away', 'Retargeted conversions from conversions that would have happened anyway'],
   [{text:'Takeovers and prospecting', options:{bold:true}}, 'Geo/time crossover: live in test cities and held out in matched cities in the Shanghai week, then swapped for the Paris week; event-strength confounding is acknowledged in the readout', 'Broad-media lift from event strength']];
  const th = table(s, rows, {x:lx, y:1.58, colW:[1.4,3.2,1.7], fontSize:8.1}); fit('S7 design', th, 2.2);
  let y=1.58+th+0.08; rect(s, lx, y, lw, 0.78, {fill:T.pale, round:true, r:0.06});
  text(s, [{text:'Intention-to-treat arithmetic. ', options:{bold:true, color:T.deep}},{text:'Treatment conversion = new payers in treatment ÷ eligible treatment users; control conversion = the same in control. Incremental new payers = (treatment − control conversion) × eligible treatment users; incremental CAC = incremental campaign cost ÷ incremental new payers. A zero or negative lift is reported as undefined and unfavourable. A paid customer already entitled to ATP is never an acquisition.'}], {x:lx+0.12, y:y+0.03, w:lw-0.24, h:0.72, fontSize:8, valign:'middle', lineSpacingMultiple:1.0});
  y+=0.86; sectionLabel(s, lx, y, lw, 'Minimum sample per arm to detect a lift (proposed readout rule)'); y+=0.3;
  const ss=M.sample_sizes; const pick=(b,l)=>ss.find(x=>Math.abs(x.baseline-b)<1e-9 && Math.abs(x.relative_lift-l)<1e-9);
  const srows=[['Baseline conversion','+30% lift','+50% lift','Eligible pool at 10% holdout (+50%)'],
    ['0.36% (CRM, P2-free, per treated user)', fmt.n(pick(0.0036,0.3).n_per_arm), fmt.n(pick(0.0036,0.5).n_per_arm), fmt.n(pick(0.0036,0.5).eligible_with_10pct_holdout)],
    ['1.0% (retargeting audience)', fmt.n(pick(0.01,0.3).n_per_arm), fmt.n(pick(0.01,0.5).n_per_arm), fmt.n(pick(0.01,0.5).eligible_with_10pct_holdout)],
    ['2.0% (lapsed 2025 buyers)', fmt.n(pick(0.02,0.3).n_per_arm), fmt.n(pick(0.02,0.5).n_per_arm), fmt.n(pick(0.02,0.5).eligible_with_10pct_holdout)]];
  const sh = table(s, srows, {x:lx, y, colW:[2.4,1.0,1.0,1.9], fontSize:8.3}); y+=sh+0.06;
  fit('S7 left', y, 6.5);
  const rx=6.95, rw=6.03; sectionLabel(s, rx, 1.26, rw, 'Scorecard: one north star plus nine supporting metrics');
  const krows=[['Metric','Definition (numerator ÷ denominator, window)','Proposed threshold'],
   [{text:'North star: D90 retained-payer rate', options:{bold:true, color:T.orange}}, 'Incremental new payers who at day 90 hold a paid ATP entitlement and made ≥ 1 qualified view in days 61-90 ÷ incremental new payers acquired ≥ 90 days earlier; if days 61-90 fall in the off-season, the window is the first 30 days of the 2027 season', '≥ 30%'],
   [{text:'Contribution per acquired payer', options:{bold:true}}, 'Contribution before marketing ÷ attributed new payers, 12-month view (modelled, then measured); a retained user can still be uneconomic', `≥ ₹150 (base ${fmt.inr(B.value_per_new_payer_m12)})`],
   ['Attributed / incremental CAC (row C2)', 'Row spend ÷ attributed new payers; incremental cost ÷ incremental new payers (holdout)', '≤ ₹200 / ≤ ₹300'],
   ['Next-event return (leading)', 'New payers with a qualified view in the next qualifying tournament ÷ new payers whose next tournament has ended', '≥ 45%'],
   ['Upgrade share within 30 days', 'Tournament entrants buying Finish-the-Season inside 30 days ÷ entrants whose window has closed', `≥ 20% (ladder target 30%; break-even ${fmt.pct(be.be_upgrade_m24_cac183)} at 24 months)`],
   ['Behavioural / commercial retention (day 60)', 'Qualified views in ≥ 2 distinct event weeks ÷ new payers ≥ 60 days old; active paid ATP entitlement on day 60 ÷ the same base', '≥ 35% / ≥ 40%'],
   ['Renewal (matured cohorts only)', '2027 season purchases by 15 Feb ÷ 2026 Finish-the-Season holders; separately ÷ 2026 season holders', '≥ 50% / ≥ 85% (case-informed)'],
   ['Cross-sport bridge', 'Monthly Pass purchases within 14 days of ATP expiry ÷ expiring ATP-only holders', '≥ 8%'],
   ['Customer experience', 'Replay-push opens ÷ delivered; weekly opt-outs ÷ recipients; refunds ÷ purchases', '≥ 25% · < 1% · < 2%']];
  const kh = table(s, krows, {x:rx, y:1.58, colW:[1.5,3.28,1.25], fontSize:8, zebra:true}); fit('S7 kpi', kh, 4.9);
  takeaway(s, 'Marketing-caused new payers = treatment minus control, never last click. Organic F1/football demand sits inside the control group and is subtracted; subscribers already entitled to ATP are never counted as new. Because a retained user can still be uneconomic, contribution per payer sits beside the north star.');
}
// ------------------------------------------------------------------ 10 SOLUTION 8
{ const s = pres.addSlide();
  frame(s, {title:[{t:'Approve a ₹10 lakh measured pilot plus ₹4 lakh implementation; '},{t:'scale acquisition in the February 2027 wave only if three gates pass', a:true}], tag:'Solution 8 of 8', sub:'Implementation, risks and investment decision', page:10,
    sources:'Sources: CF18 (rights through 2028); S3 calendar (the February-March 2027 events are placed by their 2026 dates until the 2027 calendar is published). Implementation budget is an assumption (about 6 engineer-weeks plus analytics tooling). D90 gates apply only to cohorts observed for 90 days.'});
  const rows=[['Phase (dates, events)','Actions (accountable function)','Depends on','Gate and decision'],
   [{text:'Days 0-14 · 23 Sep-6 Oct · Chengdu/Hangzhou, Tokyo/Beijing', options:{bold:true}}, 'Replace planning pools with CRM counts; build segments and the 10% holdout (Growth analytics, CRM). Approve rate card, credits, refund policy (Commercial, Legal). Contests with ITD (Community). Morning-replay v0: CRM-only spoiler-free push (CRM, Editorial).', 'Existing CRM and editorial tools; legal review of credits; no engineering', 'G1 (day 14): holdout live, rate card signed off, control IDs loaded into ad platforms'],
   [{text:'Days 15-45 · 7 Oct-6 Nov · Shanghai, 250s, Basel/Vienna, Paris', options:{bold:true}}, 'T-48h paid rows live in marquee weeks; credit ladder live; ESPN.in geo test in the Shanghai week; morning-replay v1 (hidden scores, 20-minute cuts) when engineering ships (Product, Editorial); Race-to-Turin updates after finals.', 'Engineering: spoiler-free surfaces, timed replay automation, checkout credits (~6 engineer-weeks); ATP Media clip rights within the agreement', 'G2 (day 45): C2 attributed CAC ≤ ₹200; CRM relative lift ≥ 30%; upgrade share ≥ 12% so far. Fail: stop C1 and C6, keep owned rows'],
   [{text:'Days 46-90 · 7 Nov-21 Dec · Paris, Stockholm, ATP Finals, off-season', options:{bold:true}}, 'ATP Finals push (18:30 and 01:00 IST sessions, replay-first for the latter); season-end bridge to the Monthly Pass on 23 Nov; 2027 loyalty price opens; D30 and D45 cohort readouts.', 'Renewal SKU in checkout; Next Gen Finals date from ATP', 'G3 (day 90): next-event return ≥ 45%; upgrade share ≥ 20% for closed windows; incremental CAC ≤ ₹300'],
   [{text:'Days 91-120 · 22 Dec-20 Jan · off-season, 2027 season from 5 Jan', options:{bold:true}}, 'D90 retained-payer readout for the September-October cohorts; season-start reactivation; decision memo on the February-March wave (Feb ATP 500s, Indian Wells, Miami).', 'Matured cohorts only; 2027 calendar', 'Scale decision: G2 and G3 passed → scale C2 + C3 to ₹5-₹8 lakh a month for the wave; otherwise redesign the ladder or stop paid acquisition']];
  const th = table(s, rows, {x:MX, y:1.26, colW:[2.05,5.5,2.2,2.88], fontSize:8, zebra:true}); fit('S8 roadmap', th, 2.7);
  let y=1.26+th+0.1;
  const rw=6.35; const rrows=[['Material risk','Mitigation','Model impact'],
   ['Cannibalisation of full-price buyers by credits and the loyalty price', 'One credit per account; three sessions per tournament; loyalty price only for prior holders; monitored weekly', `${fmt.lakh(SC.base.totals.cannibalisation.m12)} base, ${fmt.lakh(SC.downside.totals.cannibalisation.m12)} downside (12 months)`],
   ['Insufficient incremental lift', 'Holdout and geo designs; stop rules at days 30 and 45; owned rows keep running', `Incremental CAC ${fmt.inr(B.paid_blended_cac_incremental)} base, ${fmt.inr(SC.downside.totals.paid_blended_cac_incremental)} downside`],
   ['Scheduling and player uncertainty (withdrawals, overnight moves)', 'Event-defined SKUs; automatic session credits; copy never promises a player', 'Refunds assumed < 2% of purchases; 2% support cost in every price'],
   ['Delivery capacity (editorial cuts, engineering)', 'Two editors on event weeks; v0 CRM-only fallback; engineering scoped to two features', 'C5 ₹1.5 lakh; ₹4 lakh one-off implementation'],
   ['Smaller eligible pools; consent limits', 'First-party consented data only; no Dream11 data; pools replaced on day 0', 'CRM totals scale linearly; paid rows unaffected']];
  const rh = table(s, rrows, {x:MX, y, colW:[2.0,2.55,1.8], fontSize:7.4, zebra:true}); fit('S8 risks', y+rh, 6.5);
  const dx=MX+rw+0.15, dw=W-MX-dx; rect(s, dx, y, dw, 6.48-y, {fill:T.paleOrange, round:true, r:0.06});
  text(s, [{text:'Investment decision (proposed). ', options:{bold:true, color:T.orange}},{text:`Approve ₹10 lakh of marketing for the nine-week pilot plus about ₹4 lakh of one-off implementation. Expected in the base case (modelled): ${fmt.n(B.new_payers_attributed_dedup)} attributed and ${fmt.n(B.incremental_new_payers)} incremental new payers, ${fmt.inr(B.paid_ex_test_cac_attributed)} attributed CAC on the scalable rows, ${fmt.lakh(SC.base.totals.net.m12)} programme net at 12 months, ${fmt.lakh(SC.base.totals.acq_net.m24)} on the scalable rows within the rights horizon.`, options:{breakLine:true}},
           {text:'First accountable actions (this week): ', options:{bold:true, color:T.deep}},{text:'Growth analytics loads CRM counts and the holdout; Commercial signs the rate card and credit terms; Product scopes the two engineering features; Editorial books the event-week editors.', options:{breakLine:true}},
           {text:'Evidence required to expand: ', options:{bold:true, color:T.deep}},{text:'G2 and G3 passed on measured, not attributed, data.', options:{breakLine:true}},
           {text:'Next 12 months: ', options:{bold:true, color:T.deep}},{text:'the February-March 2027 wave (500s, Indian Wells, Miami) is funded by the scale decision; clay and grass swings run on owned channels and the ladder; 2027 season renewals in January 2028 feed the final rights year.'}], {x:dx+0.12, y:y+0.06, w:dw-0.24, h:6.48-y-0.12, fontSize:8.5, lineSpacingMultiple:1.04, paraSpaceAfter:3});
  takeaway(s, 'The smallest version that tests the proposition is CRM-only on day 0; engineering, rights approvals and the paid rows are added only as gates pass. Scale or stop is decided on day 90 with matured cohorts, and later cohorts are re-read at their own day 90.');
}
// ------------------------------------------------------------------ 11-12 REFERENCES
const ledger = fs.readFileSync(path.join(__dirname,'../research/source_ledger.csv'),'utf8');
function parseCSV(txt){ const out=[]; let row=[], cell='', q=false; for(let i=0;i<txt.length;i++){ const ch=txt[i]; if(q){ if(ch==='"'){ if(txt[i+1]==='"'){cell+='"'; i++;} else q=false; } else cell+=ch; } else { if(ch==='"') q=true; else if(ch===','){row.push(cell); cell='';} else if(ch==='\n'){ row.push(cell); out.push(row); row=[]; cell=''; } else if(ch!=='\r') cell+=ch; } } if(cell||row.length){row.push(cell); out.push(row);} return out; }
const L = parseCSV(ledger); const hdr=L[0]; const srcs = L.slice(1).filter(r=>r.length>=5).map(r=>Object.fromEntries(hdr.map((h,i)=>[h,r[i]])));
function refRows(list){ return [['ID','Organisation and title','Published / accessed','Claim supported (geography; evidence type)','URL'], ...list.map(x=>[{text:x.id, options:{bold:true, color:T.deep}}, {text:[{text:x.organisation+': ', options:{bold:true}},{text:x.title}]}, `${x.published_or_updated} / ${x.accessed}`, `${x.claim_supported} (${x.geography}; ${x.evidence_type})`, x.url && x.url.startsWith('http') ? {text:x.url.split(' ; ').map((u,i,a)=>({text:u+(i<a.length-1?'\n':''), options:{hyperlink:{url:u}, color:T.deep}})) } : x.url])]; }
{ const s = pres.addSlide();
  frame(s, {title:[{t:'References (1 of 2): '},{t:'sources with dates and links', a:true}], tag:'References', sub:'Not a solution slide', page:11, sources:'Evidence cut-off: sources published on or before 19 September 2026; accessed 21 September 2026 through search-index copies because the build environment could not open the sites directly. CF = case fact from the Round 3 brief (page indices per the case PDF). Case facts govern where public figures differ.'});
  const th = table(s, refRows(srcs.slice(0,9)), {x:MX, y:1.26, colW:[0.45,2.7,1.55,4.63,3.3], fontSize:7.8, zebra:true}); fit('Ref1', th, 5.7); }
{ const s = pres.addSlide();
  frame(s, {title:[{t:'References (2 of 2): '},{t:'sources, definitions and method notes', a:true}], tag:'References', sub:'Not a solution slide', page:12, sources:'Acronyms: ATP = Association of Tennis Professionals; CAC = customer acquisition cost; CRM = customer relationship management; CVR = conversion rate; CPC / CPM / CTR = cost per click / per thousand impressions / click-through rate; FTS = Finish-the-Season pass; GST = goods and services tax; IST = India Standard Time; ITD = Indian Tennis Daily; ITT = intention to treat; D90 = day 90 after first purchase.'});
  const th = table(s, refRows(srcs.slice(9)), {x:MX, y:1.26, colW:[0.45,2.7,1.55,4.63,3.3], fontSize:7.0, zebra:true}); fit('Ref2', th, 3.4);
  let y=1.26+th+0.1; sectionLabel(s, MX, y, 6, 'Definitions and method notes'); y+=0.3;
  const defs=[['Term','Definition used throughout the deck'],
   ['New payer', 'First-ever FanCode payment is an ATP pass in the pilot window. A first ATP purchase by an existing F1, MotoGP, LaLiga or Monthly payer is an existing-payer ATP purchase, reported separately, never a new payer.'],
   ['CAC, attributed vs incremental', 'Attributed CAC = row spend ÷ attributed new payers. Incremental CAC = spend ÷ incremental new payers (attributed × validated incremental share from the holdout or geo test). Blended CAC = spend ÷ deduplicated new payers; the harmonic form 1 ÷ Σ(wᵢ ÷ CACᵢ) is only a check across rows with the same denominator.'],
   ['Contribution before marketing', 'Price ÷ 1.18 (18% GST assumed included) − 4% of gross (gateway 2%, support and refunds 2%) − ₹2 per assumed streaming hour. Excludes the fixed, confidential ATP rights fee, so it is not profit. Credits are price reductions, never revenue; a rupee of bundle revenue appears once.'],
   ['Horizons, case observations, pools, times', '90 days, 12 and 24 months from a 7 Oct 2026 purchase; 24 months sits inside the rights term through 2028 (CF18). CF7 and CF8 are baselines with unspecified windows, so new entrants use lower, disclosed renewal assumptions. CRM pools (150k / 120k / 40k / 60k) are assumptions replaced by counts on day 0. Session times are typical of recent editions, converted with time-zone-aware tools. The brief\'s illustrative 240M/120M/24M chart is never used as an audience estimate.']];
  const dh = table(s, defs, {x:MX, y, colW:[1.9,10.73], fontSize:7.2, zebra:true}); fit('Ref2 defs', y+dh, 6.95); }
const outDir = path.join(__dirname,'out'); fs.mkdirSync(outDir,{recursive:true});
const file = path.join(outDir, `${TEAM}_BGCCR3.pptx`);
await pres.writeFile({fileName:file});
console.log('written', file); if(warnings.length){ console.log('FIT WARNINGS:'); warnings.forEach(w=>console.log('  - '+w)); } else console.log('no fit warnings');
})().catch(e=>{ console.error(e); process.exit(1); });
