#!/usr/bin/env bash
# Regenerate the intake receipt for the source dataset parts.
#
# Pure intake bookkeeping: checksums, sizes, header consistency and structural
# sanity for each part. Performs no data processing and reads no field values.
#
# Usage: bash scripts/intake_manifest.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RAW="$ROOT/data/raw_parts"
OUT="$ROOT/INTAKE.md"
EXPECTED_PARTS=10
EXPECTED_RECORDS=173119
TODAY="$(date -u +%Y-%m-%d)"

shopt -s nullglob
parts=("$RAW"/us-software-saas-companies-part-*.csv)
shopt -u nullglob

if [ ${#parts[@]} -eq 0 ]; then
  echo "No parts found in $RAW" >&2
  exit 1
fi

ref_header_md5="$(head -1 "${parts[0]}" | md5sum | cut -d' ' -f1)"
total_bytes=0
total_lines=0
present=()

rows=""
for f in "${parts[@]}"; do
  base="$(basename "$f")"
  num="${base##*part-}"; num="${num%.csv}"
  present+=("$num")
  bytes=$(stat -c %s "$f")
  lines=$(wc -l < "$f")
  sha=$(sha256sum "$f" | cut -d' ' -f1)
  hmd5=$(head -1 "$f" | md5sum | cut -d' ' -f1)
  [ "$hmd5" = "$ref_header_md5" ] && hdr="same" || hdr="**DIFFERS**"
  q=$(tr -cd '"' < "$f" | wc -c)
  [ $((q % 2)) -eq 0 ] && quotes="balanced" || quotes="**odd**"
  lb=$(tail -c 1 "$f" | od -An -tx1 | tr -d ' \n')
  [ "$lb" = "0a" ] && nl="yes" || nl="**no**"
  total_bytes=$((total_bytes + bytes))
  total_lines=$((total_lines + lines))
  rows+="| $num | \`$base\` | $(printf "%'d" "$bytes") | $(printf "%'d" "$lines") | $hdr | $quotes | $nl | \`${sha:0:16}…\` |"$'\n'
done

missing=""
for i in $(seq -w 1 "$EXPECTED_PARTS"); do
  found=no
  for p in "${present[@]}"; do [ "$p" = "$i" ] && found=yes; done
  [ "$found" = no ] && missing+="$i "
done
[ -z "$missing" ] && missing_txt="none — all $EXPECTED_PARTS parts received" || missing_txt="$missing"

{
cat <<EOF
# Source dataset parts — intake receipt

Generated by \`scripts/intake_manifest.sh\` on $TODAY (UTC). Do not hand-edit.

Project: Status Quo US B2B SaaS founder lead research.
Expected: $EXPECTED_PARTS parts of \`us-software-saas-companies-cleaned.csv\`
(~$(printf "%'d" "$EXPECTED_RECORDS") records total).

**Status: HOLDING — no data processing has started, per instruction.**

## Received

| Part | Saved filename | Bytes | Physical lines | Header | Quote parity | Trailing NL | SHA-256 |
|---|---|---:|---:|---|---|---|---|
$rows
Parts received: ${#parts[@]} of $EXPECTED_PARTS.
Missing: $missing_txt
Total on disk: $(printf "%'d" "$total_bytes") bytes across $(printf "%'d" "$total_lines") physical lines.

Every copy was verified byte-identical (sha256) against its upload at receipt time.
Full checksums:

\`\`\`
EOF
sha256sum "${parts[@]}" | sed "s|$RAW/||"
cat <<EOF
\`\`\`

## Schema

All parts carry an identical 27-column header, matching the brief:

\`\`\`
$(head -1 "${parts[0]}")
\`\`\`

Because the header repeats in every part, any concatenation must drop it for all
but the first file — or, preferably, parse each part independently.

## Structural notes recorded at intake

- Encoding: UTF-8 throughout.
- Every part ends on a newline and has balanced double-quote counts, so the split
  appears CSV-aware rather than a blind byte cut. Records do not look truncated at
  the chunk boundaries. This is a sanity signal, not a substitute for the Stage 1 audit.
- Part sizes cluster tightly at ~28 MB while line counts vary widely, which indicates
  the source was chunked by byte size, not by row count. Records per part will
  therefore be uneven.
- Physical line counts far exceed the record count implied by a ~$(printf "%'d" "$EXPECTED_RECORDS")-row
  dataset. Free-text columns (Description, Specialties, Derived Description) contain
  embedded newlines inside quoted fields. **All readers must use a real CSV parser;
  never split these files on newlines.** True record counts get established in the
  Stage 1 audit.

## Handling rules

- These files are the immutable originals: do not modify, overwrite, rename or delete.
  They are stored mode 444.
- They are gitignored via \`status_quo_lead_research/data/\` so a stray \`git add -A\`
  cannot publish third-party lead data to the public GitHub remote.
- Being gitignored, they live only on this container's disk, which is ephemeral.
  Durable retention is an open decision with the user.
EOF
} > "$OUT"

echo "Wrote $OUT"
echo "Parts: ${#parts[@]}/$EXPECTED_PARTS   Missing: $missing_txt"
